version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kidssmart
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build: .
    command: python scripts/start_api.py
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  worker:
    build: .
    command: celery -A core.etl worker --loglevel=INFO
    env_file: .env
    depends_on:
      - api
      - redis
    volumes:
      - .:/app

  dashboard:
    build: .
    command: streamlit run dashboard/app.py --server.port 8501 --server.address 0.0.0.0
    env_file: .env
    depends_on:
      - api
    ports:
      - "8501:8501"
    volumes:
      - .:/app

  beat:
    build: .
    command: celery -A core.etl beat --loglevel=INFO
    env_file: .env
    depends_on:
      - api
      - redis
      - worker
    volumes:
      - .:/app

profiles:
  prod:
    - db
    - redis
    - api
    - worker
    - beat
    - dashboard

volumes:
  db_data:
